### PR TITLE
Text modified on "become an affiliate" page

### PR DESCRIPTION
**Pull request by Crosstons**
This PR addresses issue #58 , The text has been modified as mentioned in the issue.

### CODE REVIEW

**Comment by Crosstons** [comment]
@sdaav @fricoben Can you please review?

**Comment by Crosstons** [comment]
Should I close this PR? as there is no review or activity @sdaav @fricoben

**Review by fricoben — APPROVED** [review]
lgtm

**Comment by fricoben** [comment]
@Crosstons apply to the related issue so I assign you

**Pull request merged**
