### PR TITLE
feat: update profile page & cleanup old code

### LINKED ISSUE #60: Profil page
Figma : https://www.figma.com/file/S1UKYgWewNqNHZFAaBUilG/%F0%9F%8F%9D%EF%B8%8F-Starknet-ID?type=design&node-id=3121%3A16968&mode=design&t=ZALgUe63m3e5jFo1-1

### PR DESCRIPTION
**Pull request by irisdv**
Close #60

### CODE REVIEW

**Review by fricoben — CHANGES_REQUESTED** [review]
Looks good !

Two main things: 
Capture d’écran 2024-05-01 à 16 18 28
- [ ] Font seems to not work on social media icons
- [ ] I think we can keep the navbar

**Review by Kevils — CHANGES_REQUESTED** [review]
Looks nice ! 

1 - I think we can add the same hover interaction as the main button with our shadow and movement effect
image

2 - keep navbar

3 - The twitter cta is available ?

Thanks ! :)

**Comment by irisdv** [comment]
> 3 - The twitter cta is available ?

Not yet because we need to pay to access the API in order to retrieve the username from the twitter id, so for now I disabled it. But it's ready to be enabled when we have it.

**Review by Kevils — APPROVED** [review]
Lgtm

**Pull request merged**
